In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame

# from pandas_datareader import data
from datetime import datetime, timedelta

from sqlalchemy import create_engine

import requests
import urllib

import re
import os
import logging
import time
import sys

from IPython.display import clear_output

sys.path.append('..')

import Crawler as cw

In [2]:
engines = {}
for DB_idx in range(83):
    engines[DB_idx] = create_engine('sqlite:///%s/%s%d.db' %
                         ("../BK20180301/StockInfo_otc/", 'Insti3_', DB_idx),
                         echo=False)

In [ ]:
def fixer(df):
    col_tem = ['自營買(自行)', '自營賣(自行)', '自營買賣(自行)', '自營買(避險)', '自營賣(避險)', '自營買賣(避險)']
    df[col_tem] = df[col_tem].astype(float)
    df['自營買'] = df['自營買(自行)'] + df['自營買(避險)']
    df['自營賣'] = df['自營賣(自行)'] + df['自營賣(避險)']
    df['自營買賣'] = df['自營買賣(自行)'] + df['自營買賣(避險)']
    return df

In [ ]:
paser = ['code', '證券名稱', '外資買', '外資賣', '外資買賣',
                       '投信買', '投信賣', '投信買賣',
                       '自營買(自行)', '自營賣(自行)', '自營買賣(自行)',
                       '自營買(避險)', '自營賣(避險)', '自營買賣(避險)',
                    '三大買賣', 'date']
for engine in engines.values():
    table_names = engine.table_names()
    for table_name in table_names:
        df = fixer(pd.read_sql(table_name, con=engine, columns=paser))
        df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

In [ ]:
print('OK')

In [5]:
pd.read_sql(engines[0].table_names()[0], con=engines[0])
# engines[0].table_names()[0]

,code,證券名稱,外資買,外資賣,外資買賣,投信買,投信賣,投信買賣,自營買(自行),自營賣(自行),自營買賣(自行),自營買(避險),自營賣(避險),自營買賣(避險),自營買,自營賣,自營買賣,三大買賣,date
0,1333,恩得利,0,0,0,0,0,0,0,1000,-1000,0,0,0,0,1000,-1000,-1000,2005-08-08
1,1333,恩得利,0,0,0,0,0,0,0,1000,-1000,0,0,0,0,1000,-1000,-1000,2005-08-09
2,1333,恩得利,0,0,0,0,0,0,0,1000,-1000,0,0,0,0,1000,-1000,-1000,2005-08-10
3,1333,恩得利,0,0,0,0,0,0,0,1000,-1000,0,0,0,0,1000,-1000,-1000,2005-08-11
4,1333,恩得利,0,0,0,0,0,0,0,1000,-1000,0,0,0,0,1000,-1000,-1000,2005-08-12
5,1333,恩得利,0,0,0,0,0,0,0,1000,-1000,0,0,0,0,1000,-1000,-1000,2005-08-15
6,1333,恩得利,10000,0,10000,290000,0,290000,0,276000,-276000,0,0,0,0,276000,-276000,24000,2005-08-18
7,1333,恩得利,3000,0,3000,1282000,0,1282000,0,300000,-300000,0,0,0,0,300000,-300000,985000,2005-08-19
8,1333,恩得利,3000,3000,0,2350000,0,2350000,70000,110000,-40000,0,0,0,70000,110000,-40000,2310000,2005-08-22
9,1333,恩得利,0,0,0,720000,0,720000,0,140000,-140000,0,0,0,0,140000,-140000,580000,2005-08-23
10,1333,恩得利,0,3000,-3000,1475000,0,1475000,60000,200000,-140000,0,0,0,60000,200000,-140000,1332000,2005-08-24
11,1333,恩得利,0,16000,-16000,825000,0,825000,50000,321000,-271000,0,0,0,50000,321000,-271000,538000,2005-08-25
12,1333,恩得利,0,0,0,140000,0,140000,140000,125000,15000,0,0,0,140000,125000,15000,155000,2005-08-26
13,1333,恩得利,0,0,0,150000,0,150000,90000,24000,66000,0,0,0,90000,24000,66000,216000,2005-08-29
14,1333,恩得利,0,0,0,0,0,0,110000,0,110000,0,0,0,110000,0,110000,110000,2005-08-30
15,1333,恩得利,0,0,0,350000,0,350000,120000,0,120000,0,0,0,120000,0,120000,470000,2005-08-31
16,1333,恩得利,0,0,0,0,100000,-100000,0,0,0,0,0,0,0,0,0,-100000,2005-09-02
17,1333,恩得利,0,0,0,0,0,0,0,15000,-15000,0,0,0,0,15000,-15000,-15000,2005-09-05
18,1333,恩得利,0,0,0,310000,0,310000,70000,185000,-115000,0,0,0,70000,185000,-115000,195000,2005-09-06
19,1333,恩得利,0,0,0,500000,370000,130000,36000,330000,-294000,0,0,0,36000,330000,-294000,-164000,2005-09-07
20,1333,恩得利,0,0,0,414000,0,414000,5000,73000,-68000,0,0,0,5000,73000,-68000,346000,2005-09-08
21,1333,恩得利,0,0,0,50000,35000,15000,20000,75000,-55000,0,0,0,20000,75000,-55000,-40000,2005-09-09
22,1333,恩得利,0,0,0,0,156000,-156000,23000,19000,4000,0,0,0,23000,19000,4000,-152000,2005-09-12
23,1333,恩得利,0,0,0,141000,14000,127000,64000,75000,-11000,0,0,0,64000,75000,-11000,116000,2005-09-13
24,1333,恩得利,0,0,0,150000,0,150000,0,6000,-6000,0,0,0,0,6000,-6000,144000,2005-09-14
25,1333,恩得利,0,0,0,120000,0,120000,0,0,0,0,0,0,0,0,0,120000,2005-09-15
26,1333,恩得利,0,0,0,120000,0,120000,0,0,0,0,0,0,0,0,0,120000,2005-09-16
27,1333,恩得利,0,0,0,65000,0,65000,5000,0,5000,0,0,0,5000,0,5000,70000,2005-09-19
28,1333,恩得利,0,0,0,150000,0,150000,45000,1000,44000,0,0,0,45000,1000,44000,194000,2005-09-20
29,1333,恩得利,0,0,0,131000,0,131000,8000,0,8000,0,0,0,8000,0,8000,139000,2005-09-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,1333,恩得利,0,8000,-8000,0,0,0,0,0,0,0,0,0,00,00,00,-8000,2016-01-27
988,1333,恩得利,0,2000,-2000,0,0,0,0,0,0,0,0,0,00,00,00,-2000,2016-01-29
989,1333,恩得利,0,8000,-8000,0,0,0,0,0,0,0,0,0,00,00,00,-8000,2016-02-01
990,1333,恩得利,0,13000,-13000,0,0,0,0,0,0,0,0,0,00,00,00,-13000,2016-02-03
991,1333,恩得利,0,3000,-3000,0,0,0,0,0,0,0,0,0,00,00,00,-3000,2016-02-15
992,1333,恩得利,6000,0,6000,0,0,0,0,0,0,0,0,0,00,00,00,6000,2016-02-16
993,1333,恩得利,1000,0,1000,0,0,0,0,0,0,0,0,0,00,00,00,1000,2016-02-17
994,1333,恩得利,0,7000,-7000,0,0,0,0,0,0,0,0,0,00,00,00,-7000,2016-02-18
995,1333,恩得利,0,101,-101,0,0,0,0,0,0,0,0,0,00,00,00,-101,2016-02-26
996,1333,恩得利,23000,0,23000,0,0,0,0,0,0,0,0,0,00,00,00,23000,2016-03-01
997,1333,恩得利,35000,4000,31000,0,0,0,0,0,0,0,0,0,00,00,00,31000,2016-03-04
998,1333,恩得利,0,22000,-22000,0,0,0,0,0,0,0,0,0,00,00,00,-22000,2016-03-07
999,1333,恩得利,4004,15000,-10996,0,0,0,0,0,0,0,0,0,00,00,00,-10996,2016-03-08
1000,1333,恩得利,0,12000,-12000,0,0,0,0,0,0,0,0,0,00,00,00,-12000,2016-03-09
1001,1333,恩得利,1,2000,-1999,0,0,0,0,0,0,0,0,0,00,00,00,-1999,2016-03-10
1002,1333,恩得利,22000,0,22000,0,0,0,0,0,0,0,0,0,00,00,00,22000,2016-03-11
1003,1333,恩得利,0,29000,-29000,0,0,0,0,0,0,0,0,0,00,00,00,-29000,2016-03-15
1004,1333,恩得利,7000,0,7000,0,0,0,0,0,0,0,0,0,00,00,00,7000,2016-03-18
1005,1333,恩得利,1000,7000,-6000,0,0,0,0,0,0,0,0,0,00,00,00,-6000,2016-03-21
1006,1333,恩得利,5000,1000,4000,0,0,0,0,0,0,0,0,0,00,00,00,4000,2016-03-23
1007,1333,恩得利,0,2000,-2000,0,0,0,0,0,0,0,0,0,00,00,00,-2000,2016-03-24
1008,1333,恩得利,14000,3000,11000,0,0,0,0,0,0,0,0,0,00,00,00,11000,2016-03-29
1009,1333,恩得利,4000,5000,-1000,0,0,0,0,0,0,0,0,0,00,00,00,-1000,2016-03-30
1010,1333,恩得利,0,1000,-1000,0,0,0,0,0,0,0,0,0,00,00,00,-1000,2016-04-01
1011,1333,恩得利,0,12000,-12000,0,0,0,0,0,0,0,0,0,00,00,00,-12000,2016-04-06
1012,1333,恩得利,1,0,1,0,0,0,0,0,0,0,0,0,00,00,00,1,2017-03-01
1013,1333,恩得利,0,2400,-2400,0,0,0,0,0,0,0,0,0,00,00,00,-2400,2017-03-02
1014,1333,恩得利,1,0,1,0,0,0,0,0,0,0,0,0,00,00,00,1,2017-03-29
1015,1333,恩得利,1,0,1,0,0,0,0,0,0,0,0,0,00,00,00,1,2017-04-20
1016,1333,恩得利,1,0,1,0,0,0,0,0,0,0,0,0,00,00,00,1,2017-04-28